meal_planner/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("meals/", include("meals.urls")),
    path("recipes/", include("recipes.urls")),
    path("ingredients/", include("ingredients.urls")),
    path("inventory/", include("inventory.urls")),
    path("orders/", include("orders.urls")),
    path("", RedirectView.as_view(pattern_name="meals", permanent=False)),
]

meals/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.meal_list, name="meals"),
    path("<int:pk>/edit/", views.MealEditView.as_view(), name="edit_meal"),
    path("<int:pk>/delete/",
         views.MealDeleteView.as_view(),
         name="delete_meal"),
    path("<int:pk>/add_fruits_and_veggies/",
         views.add_fruits_and_veggies,
         name="add_fruits_and_veggies"),
    path("<int:meal_pk>/fruit/create/",
         views.FruitCreateView.as_view(),
         name="create_fruit"),
    path("<int:meal_pk>/vegetable/create/",
         views.VeggieCreateView.as_view(),
         name="create_vegetable"),
    path("schedule/", views.meal_create_view, name="schedule_meal"),
    path("print/", views.print_meals, name="print_meal"),
]

recipes/urls.py
from django.urls import path
from recipes import views


urlpatterns = [
    path("", views.recipe_list, name="recipes"),
    path("create/", views.recipe_create_view, name="create_recipe"),
    path("<int:pk>/update/",
         views.RecipeEditView.as_view(),
         name="update_recipe"),
    path("<int:pk>/delete/",
         views.RecipeDeleteView.as_view(),
         name="delete_recipe"),
    path("<int:recipe_pk>/ingredients/add",
         views.add_ingredient,
         name="add_ingredient"),
    path("<int:recipe_pk>/ingredients/<int:pk>/edit/",
         views.RecipeIngredientEditView.as_view(),
         name="edit_recipe_ingredient"),
    path("<int:recipe_pk>/ingredients/<int:pk>/delete/",
         views.recipe_ingredient_delete_view,
         name="delete_recipe_ingredient"),
]

recipes/models.py
from django.db import models
from django.core.validators import MinValueValidator
from ingredients.models import Ingredient


class Recipe(models.Model):
    name = models.CharField(max_length=150)
    is_active = models.BooleanField(default=True)
    ingredients = models.ManyToManyField(
        Ingredient,
        related_name="recipes",
        through="RecipeIngredient",
        limit_choices_to={"type": "standard"}
    )

    def __str__(self):
        return self.name.title()


class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient,
                                   on_delete=models.CASCADE,
                                   limit_choices_to={"type": "standard"})
    serving = models.FloatField(
        validators=[MinValueValidator(0, message="Must be zero or larger")]
        )

    def __str__(self):
        return f"{self.ingredient} for {self.recipe}"

    class Meta:
        unique_together = ["recipe", "ingredient"]
        ordering = ["id"]

recipes/forms.py
from django.forms import ModelForm

from recipes.models import Recipe, RecipeIngredient


class RecipeForm(ModelForm):
    class Meta:
        model = Recipe
        fields = ["name"]


class RecipeIngredientForm(ModelForm):
    class Meta:
        model = RecipeIngredient
        fields = ["ingredient", "serving"]
        labels = {
            "ingredient": "Ingredient to Add",
            "serving": "Amount per person"
        }

recipes/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.views.generic.edit import UpdateView, DeleteView
from django.db import IntegrityError

from recipes.models import (
  Recipe,
  RecipeIngredient,
)
from recipes.forms import (
    RecipeForm,
    RecipeIngredientForm,
)


# TODO - Change this into a Class View
@login_required
def recipe_list(request):
    recipes = Recipe.objects.all().order_by("-is_active")
    context = {
        "section": "recipes",
        "recipes": recipes,
    }
    return render(request, "recipes/list.html", context)


# TODO - Change this into a Class View
@login_required
def recipe_create_view(request):
    if request.method == "POST":
        form = RecipeForm(request.POST)
        if form.is_valid():
            recipe = form.save()
            messages.success(request, "Recipe created.")
            return redirect(reverse("update_recipe", args=[recipe.id]))
    else:
        form = RecipeForm()
        context = {"section": "recipes", "form": form}
        return render(request, "recipes/create.html", context)


class RecipeEditView(LoginRequiredMixin, UpdateView):
    model = Recipe
    fields = ["name", "is_active"]
    template_name = "recipes/update.html"
    success_url = reverse_lazy("recipes")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["section"] = "recipes"
        # Form for adding ingredients
        context["ingredient_form"] = RecipeIngredientForm()
        return context


class RecipeDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipe
    success_url = reverse_lazy("recipes")
    template_name = "recipes/delete.html"


@login_required
def add_ingredient(request, recipe_pk):
    if request.method == "POST":
        form = RecipeIngredientForm(request.POST)
        if form.is_valid():
            ingredient = form.save(commit=False)
            recipe = Recipe.objects.get(pk=recipe_pk)
            ingredient.recipe = recipe
            try:
                ingredient.save()
            except IntegrityError:
                messages.add_message(request,
                                     messages.ERROR,
                                     "That ingredient has already been added.")
            else:
                messages.success(request, "Ingredient added.")
        else:
            messages.add_message(request,
                                 messages.ERROR,
                                 "Something went wrong.")
    return redirect(reverse("update_recipe", args=[recipe_pk]))


class RecipeIngredientEditView(LoginRequiredMixin, UpdateView):
    model = RecipeIngredient
    fields = ["ingredient", "serving"]
    template_name = "recipe_ingredients/update.html"
    success_url = reverse_lazy("recipes")

    def get_success_url(self):
        url = reverse("update_recipe", args=[self.object.recipe.id])
        return url


# TODO - Change this into a Class View (I'm not sure if I should change this. It definitely seems like it is overly simplified)
@login_required
def recipe_ingredient_delete_view(request, recipe_pk, pk):
    RecipeIngredient.objects.get(pk=pk).delete()
    return redirect(reverse("update_recipe", args=[recipe_pk]))

recipes/templates/recipes/create.html
{% extends "base.html" %}

{% block content %}
  <main class="mt-4">
    <div class="container">
      <div class="content">
        <h1 class="title">Create recipe</h1>
      </div>
      <div class="columns">
        <div role="region" aria-label="Recipe form information" class="column is-one-third">
          <p>Create a new recipe using the form to the right.</p>
        </div>
        <div role="region" aria-label="Recipe creation form" class="column is-one-quarter box">
          <form method="post">
            {{ form.as_bulma }}
            {% csrf_token %}
            <div class="controls">
              <button class="button is-primary mt-4">Create recipe</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

recipes/templates/recipes/delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-4">
    <div class="columns content is-centered">
      <div class="column is-one-third">
        <h1>Delete Recipe</h1>
        <p>
          Are you sure you want to delete {{ object }}
        </p>
        <form action="{% url "delete_recipe" object.id %}" method="post">
          {% csrf_token %}
          <div class="buttons">
            <input class="button is-danger is-outlined has-text-centered" type="submit" value="Yes">
            <a class="button is-black is-outlined" style="align-items: baseline;" href="{% url "update_recipe" object.id %}">No</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

recipes/templates/recipes/list.html
{% extends "base.html" %}

{% block content %}
  <main class="mt-4">
    <div class="container">
      <div class="content">
        <h1 class="title">Recipes</h1>
      </div>
      <div class="columns">
        <div role="region" aria-label="Recipe list information" class="column is-one-quarter">
          <a class="button is-info is-outlined mb-4" href="{% url "create_recipe" %}">New Recipe</a>
          <p>A list of all of the recipes both active and inactive.</p>
          <p>
            {% comment %} Future Features
            <ul class="list">
              <li> - </li>
              <li> - </li>
              <li> - </li>
            </ul> {% endcomment %}
          </p>
        </div>
        <div role="region" aria-label="Recipe list" class="column is-three-quarters box">
          <table class="table is-striped is-hoverable">
            <thead>
              <tr>
                <th> Name</th>
                <th>Ingredient Count</th>
                <th>Status</th>
                <th>Ingredients</th>
                <th></th>
              </tr>
            </thead>
            {% for recipe in recipes %}
              {% with ingredients=recipe.ingredients.all %}
                <tr>
                  <td>{{ recipe.name.title }}</td>
                  <td>{{ ingredients.count }}</td>
                  <td>{% if recipe.is_active %}Active{% else %}Inactive{% endif %}</td>
                  <td>
                    {% for ingredient in ingredients.all %}
                      {% if forloop.last %}
                        {{ ingredient.name }}
                      {% else %}
                        {{ ingredient.name }},
                      {% endif %}
                    {% endfor %}
                  </td>
                  <td>
                    <a class="button is-text" href={% url "update_recipe" recipe.id %}>Edit</a>
                  </td>
                </tr>
              {% endwith %}
            {% endfor %}
          </table>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

recipes/templates/recipes/update.html
{% extends "base.html" %}

{% block content %}
  <main class="mt-4">
    <div class="container">
      <div class="content">
        <h1 class="title">Update recipe</h1>
      </div>
      <div class="columns">
        <div role="region" aria-label="Recipe update directions" class="column is-one-quarter">
          <p>Use the form to the right to update this recipe.</p>
        </div>
        <div role="region" aria-label="Recipe update form" class="column is-half">
          <div class="content box">
            <div class="columns">
              <div class="column">
                <form method="post">
                  {{ form.as_bulma }}
                  {% csrf_token %}
                  <input class="button is-primary is-outlined mt-4 mr-4" type="submit" value="Done">
                  <a class="button is-danger is-outlined mt-4" style="align-items: baseline;" href={% url "delete_recipe" object.id %}>Delete</a>
                </form>
              </div>
              <div class="column">
                <form method="post" action="{% url "add_ingredient" recipe.id %}">
                  {{ ingredient_form.as_bulma}}
                  {% csrf_token %}
                  <input class="button is-primary is-outlined mt-4 mr-4" type="submit" value="Add">
                  <a class="button is-info is-outlined mt-4" href="{% url "create_ingredient" object.id %}">Create New Ingredient</a>
                </form>
              </div>
            </div>
          </div>
          <div class="content box">
            <p class="label">Ingredients:</p>
            <table class="table">
              <th>Ingredient</th>
              <th>Amount per person</th>
              <th></th>
              <th></th>
              {% for recipe_ingredient in recipe.recipeingredient_set.all %}
                <tr>
                  <td>{{ recipe_ingredient.ingredient }}</td>
                  <td>{{ recipe_ingredient.serving }} {{ recipe_ingredient.ingredient.uom}}</td>
                  <td><a class="button is-text" href="{% url "edit_recipe_ingredient" recipe.id recipe_ingredient.id%}">Edit</a></td>
                  <td><a class="button is-text" href="{% url "delete_recipe_ingredient" recipe.id recipe_ingredient.id %}">Remove</a></td>
                </tr>
              {% empty %}
                <tr>
                  <td>---</td>
                  <td>---</td>
                </tr>
              {% endfor %}
            </table>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}