meal_planner/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("meals/", include("meals.urls")),
    path("recipes/", include("recipes.urls")),
    path("ingredients/", include("ingredients.urls")),
    path("inventory/", include("inventory.urls")),
    path("orders/", include("orders.urls")),
    path("", RedirectView.as_view(pattern_name="meals", permanent=False)),
]

meals/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.meal_list, name="meals"),
    path("<int:pk>/edit/", views.MealEditView.as_view(), name="edit_meal"),
    path("<int:pk>/delete/",
         views.MealDeleteView.as_view(),
         name="delete_meal"),
    path("<int:pk>/add_fruits_and_veggies/",
         views.add_fruits_and_veggies,
         name="add_fruits_and_veggies"),
    path("<int:meal_pk>/fruit/create/",
         views.FruitCreateView.as_view(),
         name="create_fruit"),
    path("<int:meal_pk>/vegetable/create/",
         views.VeggieCreateView.as_view(),
         name="create_vegetable"),
    path("schedule/", views.meal_create_view, name="schedule_meal"),
    path("print/", views.print_meals, name="print_meal"),
]

orders/urls.py
from django.urls import path
from orders import views


urlpatterns = [
    path("orders/",
         views.OrderListView.as_view(),
         name="orders"),
    path("orders/create",
         views.OrderCreateView.as_view(),
         name="create_order"),
    path("orders/<int:pk>/update",
         views.OrderUpdateView.as_view(),
         name="update_order"),
    path("orders/<int:pk>/add_meals",
         views.add_meals_to_order,
         name="add_meals_to_order"),
    path("orders/<int:pk>/remove/<int:meal_pk>/",
         views.remove_meal_from_order,
         name="remove_meal_from_order"),
    path("orders/print/",
         views.print_orders,
         name="print_orders"),
]

orders/models.py
from django.db import models


class Order(models.Model):
    date = models.DateField()
    is_complete = models.BooleanField(default=False)

    class Meta:
        ordering = ["id", "-is_complete"]

    def get_ingredients(self):
        order_ingredients = {}

        for meal in self.meals.all():
            meal_ingredients = meal.get_ingredients()
            for ingredient, [amount, uom] in meal_ingredients.items():
                if order_ingredients.get(ingredient):
                    order_ingredients[ingredient][0] += amount
                else:
                    order_ingredients[ingredient] = [amount, uom]

        return order_ingredients

    def get_meal_count(self):
        return self.meals.count()

orders/forms.py
from django import forms
from meals.models import Meal
from orders.models import Order


class MealOrderForm(forms.Form):
    meals = forms.ModelMultipleChoiceField(
        queryset=Meal.objects.filter(order=None),
        widget=forms.CheckboxSelectMultiple()
    )

    class Meta:
        labels = {
            "meals": "Meals not on any orders:",
        }


class OrderUpdateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["date", "is_complete"]
        labels = {
            "is_complete": "Purchased"
        }

orders/views.py
import io
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView, CreateView
from django.views.generic.list import ListView
from django.urls import reverse, reverse_lazy
from django.http import FileResponse
from datetime import datetime

from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch

from meals.models import Meal
from orders.models import Order
from orders.forms import (
    MealOrderForm,
    OrderUpdateForm
)


class OrderListView(LoginRequiredMixin, ListView):
    model = Order
    template_name = "orders/list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["section"] = "orders"
        return context


class OrderCreateView(LoginRequiredMixin, CreateView):
    model = Order
    fields = ["date"]
    template_name = "orders/create.html"

    def get_success_url(self):
        return reverse("update_order", args=[self.object.id])


class OrderUpdateView(LoginRequiredMixin, UpdateView):
    model = Order
    form_class = OrderUpdateForm
    template_name = "orders/update.html"
    success_url = reverse_lazy("orders")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["meal_form"] = MealOrderForm()
        context["section"] = "orders"
        meal_count = context["meal_form"].fields["meals"].queryset.count()
        context["no_meals"] = meal_count == 0
        return context


@login_required
def add_meals_to_order(request, pk):
    if request.method == "POST":
        form = MealOrderForm(request.POST)
        if form.is_valid():
            meals = form.cleaned_data["meals"]
            order = Order.objects.get(pk=pk)
            for meal in meals:
                meal.order = order
                meal.save()
    return redirect(reverse("update_order", args=[pk]))


@login_required
def remove_meal_from_order(request, pk, meal_pk):
    meal = Meal.objects.get(pk=meal_pk)
    order = Order.objects.get(pk=pk)
    order.meals.remove(meal)
    return redirect(reverse("update_order", args=[pk]))


@login_required
def print_orders(request):
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib import colors
    from reportlab.platypus import Paragraph, Frame, Table, TableStyle

    buffer = io.BytesIO()
    p = canvas.Canvas(buffer, pagesize=letter)
    p.setTitle("Order List")
    p.setFont("Helvetica", 10)

    today = datetime.now().date()
    orders = Order.objects.filter(date__gte=today)

    styles = getSampleStyleSheet()
    title_style = styles["Title"]

    for order in orders:
        story = []

        story.append(Paragraph("Purchase Order", title_style))

        header_data = [
            ["Order #:", order.id]
        ]
        header_table = Table(
            header_data,
            colWidths=("*", 1.5*inch),
            spaceAfter=0.5*inch,
            spaceBefore=0.5*inch
        )

        header_table.setStyle(TableStyle([
            ("ALIGN", (0, 0), (0, -1), "RIGHT"),
            ("LINEBELOW", (1, 0), (1, -1), 0.25, colors.black),
        ]))

        story.append(header_table)

        ingredient_data = [[
            "Ingredients",
            "Amount",
            "Have",
            "Need",
        ]]

        ingredients = order.get_ingredients()

        for ingredient, [amount, uom] in ingredients.items():
            ingredient_data.append([
                ingredient.title(),
                f"{amount} {uom}",
            ])

        ingredient_table = Table(
            ingredient_data, colWidths=(4*inch, "*", "*", "*")
        )
        ingredient_table.setStyle(TableStyle([
            ("BOX", (0, 0), (-1, -1), 0.25, colors.black),
            ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.black),
            ("LINEBELOW", (0, 0), (-1, 0), 2, colors.black),
            ("LINEBELOW", (0, 0), (-1, 0), 2, colors.black),
            ("ALIGN", (1, 0), (-1, 0), "CENTER")
        ]))

        story.append(ingredient_table)
        f = Frame(0.5*inch, 0.5*inch, 7.5*inch, 10*inch)
        f.hAlign = "LEFT"
        f.addFromList(story, p)
        p.showPage()

    p.save()

    buffer.seek(0)
    return FileResponse(buffer, filename='orders.pdf')

orders/templates/orders/create.html
{% extends "base.html" %}

{% block content %}
  <main class="mt-4">
    <div class="container">
      <div class="content">
        <h1 class="title">Create order</h1>
      </div>
      <div class="columns">
        <div role="region" aria-label="Order form information" class="column is-one-third">
          <p>Create a new order using the form to the right.</p>
          <p>Meals can be added to the order in the next step</p>
        </div>
        <div role="region" aria-label="Order creation form" class="column is-one-quarter box">
          <form method="post">
            {{ form.as_bulma }}
            {% csrf_token %}
            <div class="controls">
              <button class="button is-primary mt-4">Create Order</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

orders/templates/orders/list.html
{% extends "base.html" %}

{% block content %}
  <main class="mt-4">
    <div class="container">
      <div class="content">
        <h1 class="title">Orders</h1>
      </div>
      <div class="columns">
        <div role="region" aria-label="Order list information" class="column is-one-quarter">
          <div class="buttons">
            <a class="button is-info is-outlined" href="{% url "create_order" %}">New Order</a>
            <a class="button is-info is-outlined" target="_blank" href="{% url "print_orders" %}">Print Orders</a>
          </div>
          <p>A list of all orders.</p>
          <p>
            {% comment %} <p class="mt-4">Planned Features</p>
            <ul>
              <li> - Ability to see if a meal has been purchased or not</li>
              <li> - Ability to filter meals</li>
            </ul> {% endcomment %}
          </p>
        </div>
        <div role="region" aria-label="Order list" class="column is-three-quarters box">
          <table class="table is-striped is-hoverable is-fullwidth">
            <thead>
              <tr>
                <th>Order #</th>
                <th>Date</th>
                <th>Completed</th>
                <th>Meals in Order</th>
                <th></th>
              </tr>
            </thead>
            {% for order in order_list %}
              <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.date }}</td>
                <td>
                  {% if order.is_complete %}
                    Yes
                  {% else %}
                    No
                  {% endif %}
                </td>
                <td>{{ order.meals.count }}</td>
                <td><a class="button is-text" href={% url "update_order" order.id %}>Edit</a></td>
              </tr>
            {% endfor %}
          </table>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

orders/templates/orders/update.html
{% extends "base.html" %}

{% block content %}
  <main class="mt-4">
    <div class="container">
      <div class="content">
        <h1 class="title">Update order</h1>
      </div>
      <div class="columns">
        <div role="region" aria-label="Order update directions" class="column is-one-quarter">
          <p>Use the form to the right to update this order.</p>
        </div>
        <div role="region" aria-label="Order update form" class="column is-half">
          <div class="content box">
            <div class="columns">
              <div class="column">
                <form method="post">
                  {{ form.as_bulma }}
                  {% csrf_token %}
                  <input class="button is-primary is-outlined mt-4 mr-4" type="submit" value="Done">
                  {% comment %} <a class="button is-danger is-outlined mt-4" style="align-items: baseline;" href={% url "delete_recipe" object.id %}>Delete</a> {% endcomment %}
                </form>
              </div>
              <div class="column">
                <form method="post" action="{% url "add_meals_to_order" object.id%}">
                  {{ meal_form.as_bulma}}
                  {% if no_meals %}
                    <p>No meals to add to order.</p>
                  {% else %}
                    <input class="button is-primary is-outlined mt-4 mr-4" type="submit" value="Add">
                  {% endif %}
                  {% csrf_token %}
                </form>
              </div>
            </div>
          </div>
          <div class="content box">
            <p class="label">Meals Added to Order:</p>
            <table class="table">
              <th>Date</th>
              <th>Meal</th>
              <th></th>
              {% for meal in order.meals.all %}
                <tr>
                  <td>{{ meal.date }}</td>
                  <td>{{ meal.recipe }}</td>
                  <td><a class="button is-text" href="{% url "remove_meal_from_order" object.id meal.id %}">Remove</a></td>
                </tr>
              {% empty %}
                <tr>
                  <td>---</td>
                  <td>---</td>
                </tr>
              {% endfor %}
            </table>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}