meal_planner/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("meals/", include("meals.urls")),
    path("recipes/", include("recipes.urls")),
    path("ingredients/", include("ingredients.urls")),
    path("inventory/", include("inventory.urls")),
    path("orders/", include("orders.urls")),
    path("", RedirectView.as_view(pattern_name="meals", permanent=False)),
]

meals/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.meal_list, name="meals"),
    path("<int:pk>/edit/", views.MealEditView.as_view(), name="edit_meal"),
    path("<int:pk>/delete/",
         views.MealDeleteView.as_view(),
         name="delete_meal"),
    path("<int:pk>/add_fruits_and_veggies/",
         views.add_fruits_and_veggies,
         name="add_fruits_and_veggies"),
    path("<int:meal_pk>/fruit/create/",
         views.FruitCreateView.as_view(),
         name="create_fruit"),
    path("<int:meal_pk>/vegetable/create/",
         views.VeggieCreateView.as_view(),
         name="create_vegetable"),
    path("schedule/", views.meal_create_view, name="schedule_meal"),
    path("print/", views.print_meals, name="print_meal"),
]

meals/models.py
from django.db import models
from django.core.validators import MinValueValidator


class Meal(models.Model):
    date = models.DateField()
    recipe = models.ForeignKey(
        "recipes.Recipe",
        related_name="meal",
        on_delete=models.CASCADE
    )
    planned = models.SmallIntegerField(
        null=True, blank=True,
        validators=[MinValueValidator(0, message="Must be zero or larger")]
    )
    actual = models.SmallIntegerField(
        null=True, blank=True,
        validators=[MinValueValidator(0, message="Must be zero or larger")]
    )
    order = models.ForeignKey(
        "orders.Order",
        null=True, blank=True,
        related_name="meals",
        on_delete=models.PROTECT
    )
    fruit = models.ForeignKey("ingredients.Ingredient",
                              on_delete=models.PROTECT,
                              null=True, blank=True,
                              related_name="meal_fruit",
                              limit_choices_to={"type": "fruit"})
    fruit_serving = models.FloatField(
        null=True,
        blank=True,
        default=0,
        validators=[MinValueValidator(0, message="Less than zero not allowed")]
    )
    vegetable = models.ForeignKey("ingredients.Ingredient",
                                  on_delete=models.PROTECT,
                                  null=True, blank=True,
                                  related_name="meal_vegatable",
                                  limit_choices_to={"type": "vegetable"})
    vegetable_serving = models.FloatField(null=True, blank=True, default=0)

    # TODO - Make it so that meals are ordered by date (Looks like this might already be the case)
    class Meta:
        ordering = ["date", "-actual"]

    def __str__(self):
        return f"{self.recipe.name} on {self.date}"

    def get_ingredients(self):
        ingredients = {}
        recipe_ingredients = self.recipe.recipeingredient_set
        if self.planned:
            planned = self.planned
        else:
            planned = 0

        for recipe_ingredient in recipe_ingredients.all():
            ingredient = recipe_ingredient.ingredient.name
            amount = round(recipe_ingredient.serving * planned)
            uom = recipe_ingredient.ingredient.uom
            if ingredient == "vegetable" and self.vegetable:
                ingredient = self.vegetable.name
                amount = round(self.vegetable_serving * planned)
                uom = self.vegetable.uom
            elif ingredient == "fruit" and self.fruit:
                ingredient = self.fruit.name
                amount = round(self.fruit_serving * planned)
                uom = self.fruit.uom
            if ingredients.get(ingredient):
                ingredients[ingredient][0] += amount
            else:
                ingredients[ingredient] = [amount, uom]
        return ingredients


class MealIngredient(models.Model):
    meal = models.ForeignKey(Meal, on_delete=models.CASCADE)
    Ingredient = models.ForeignKey("ingredients.Ingredient",
                                   on_delete=models.CASCADE)
    total = models.PositiveSmallIntegerField()
    put_out = models.PositiveSmallIntegerField()
    left_over = models.PositiveSmallIntegerField()

meals/forms.py
from django import forms
from django.forms import ModelForm, Form
from django.core.validators import MinValueValidator

from meals.models import Meal
from ingredients.models import Ingredient


class MealForm(ModelForm):
    class Meta:
        model = Meal
        fields = ["date", "recipe", "planned"]


class FruitAndVeggieForm(Form):
    vegetable = forms.ModelChoiceField(
        queryset=Ingredient.objects.filter(type="vegetable"),
        required=False
    )
    vegetable_quantity = forms.FloatField(
        required=False,
        label="Amount per person",
        validators=[MinValueValidator(0, message="Must be zero or greater")]
    )
    fruit = forms.ModelChoiceField(
        queryset=Ingredient.objects.filter(type="fruit"),
        required=False
    )
    fruit_quantity = forms.FloatField(
        required=False,
        label="Amount per person",
        validators=[MinValueValidator(0, message="Must be zero or greater")]
    )


class FruitForm(ModelForm):
    class Meta:
        model = Ingredient
        fields = ["name", "uom"]
        labels = {
            "uom": "Unit of Measure:"
        }

meals/views.py
import io
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.urls import reverse, reverse_lazy
from django.http import FileResponse
from datetime import datetime

from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch

from meals.models import Meal
from meals.forms import (
    MealForm,
    FruitAndVeggieForm,
)
from ingredients.models import (
    Ingredient,
)


# TODO - Change this into a Class View
@login_required
def meal_list(request):
    today = datetime.now().date()
    # TODO Make it so that all of the meals are shown in the list (Add pagination?)
    meals = Meal.objects.filter(date__gte=today)
    context = {
        "section": "meals",
        "meals": meals,
    }
    return render(request, "meals/list.html", context)


# TODO - Make is so that this view only shows fruits or veggies if they are part of the
# recipe the meal has
class MealEditView(LoginRequiredMixin, UpdateView):
    model = Meal
    fields = ["date",
              "recipe",
              "planned",
              "actual",
              "fruit",
              "fruit_serving",
              "vegetable",
              "vegetable_serving"]
    template_name = "meals/update.html"
    success_url = reverse_lazy("meals")


class MealDeleteView(LoginRequiredMixin, DeleteView):
    model = Meal
    success_url = reverse_lazy("meals")
    template_name = "meals/delete.html"


# TODO - Change this into a Class View
@login_required
def meal_create_view(request):
    if request.method == "POST":
        meal_form = MealForm(request.POST)
        if meal_form.is_valid():
            meal = meal_form.save()
            fruit = Ingredient.objects.get(name="fruit")
            veggie = Ingredient.objects.get(name="vegetable")
            ingredients = meal.recipe.ingredients.all()
            messages.add_message(request, messages.SUCCESS, "Meal scheduled.")
            if fruit in ingredients or veggie in ingredients:
                return redirect(reverse("add_fruits_and_veggies",
                                        args=[meal.id]))
            else:
                return redirect(reverse("meals"))
    else:

        last_meal = Meal.objects.all().order_by("id").last()
        if last_meal:
            default_planned = last_meal.planned
        else:
            default_planned = 0
        meal_form = MealForm(initial={"planned": default_planned})
    context = {
        "section": "meals",
        "form": meal_form,
    }
    return render(request, "meals/create.html", context)


@login_required
def add_fruits_and_veggies(request, pk):
    meal = Meal.objects.get(pk=pk)
    ingredients = meal.recipe.ingredients.all()
    fruit = Ingredient.objects.get(name="fruit")
    veggie = Ingredient.objects.get(name="vegetable")
    has_veggies = veggie in ingredients
    has_fruit = fruit in ingredients
    context = {
        "meal": meal,
        "has_veggies": has_veggies,
        "has_fruit": has_fruit
    }

    if request.method == "GET":
        context["form"] = FruitAndVeggieForm()
    else:
        form = FruitAndVeggieForm(request.POST)
        if form.is_valid():
            if has_fruit:
                meal.fruit = form.cleaned_data["fruit"]
                meal.fruit_serving = form.cleaned_data["fruit_quantity"]
            if has_veggies:
                meal.vegetable = form.cleaned_data["vegetable"]
                meal.vegetable_serving = (
                    form.cleaned_data["vegetable_quantity"]
                )
            meal.save()
            return redirect("meals")
        else:
            context["form"] = form

    return render(request, "meals/add.html", context)


class FruitCreateView(LoginRequiredMixin, CreateView):
    model = Ingredient
    fields = ["name", "uom"]
    template_name = "ingredients/fruit.html"

    def get_success_url(self):
        url = reverse("add_fruits_and_veggies",
                      args=[self.kwargs.get("meal_pk")])
        return url

    def form_valid(self, form):
        fruit = form.save(commit=False)
        fruit.type = "fruit"
        fruit.save()
        return redirect(self.get_success_url())


class VeggieCreateView(LoginRequiredMixin, CreateView):
    model = Ingredient
    fields = ["name", "uom"]
    template_name = "ingredients/veggie.html"

    def get_success_url(self):
        url = reverse("add_fruits_and_veggies",
                      args=[self.kwargs.get("meal_pk")])
        return url

    def form_valid(self, form):
        veggie = form.save(commit=False)
        veggie.type = "vegetable"
        veggie.save()
        return redirect(self.get_success_url())


# TODO - Make it so that the user chooses what meals they want to print before the
# meals are printed out
@login_required
def print_meals(request):
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib import colors
    from reportlab.platypus import Paragraph, Frame, Table, TableStyle

    buffer = io.BytesIO()
    p = canvas.Canvas(buffer, pagesize=letter)
    p.setTitle("Meal List")
    p.setFont("Helvetica", 10)

    today = datetime.now().date()
    meals = Meal.objects.filter(date__gte=today)

    styles = getSampleStyleSheet()
    title_style = styles["Title"]

    for meal in meals:
        story = []

        story.append(Paragraph("Record Sheet", title_style))

        name = meal.recipe.name.title()

        header_data = [
            ["Meal:", name],
            ["Date:", meal.date],
            ["# of pans of main dish:", ""],
            ["# of pans left:", ""]
        ]
        header_table = Table(
            header_data,
            colWidths=("*", 1.5*inch),
            spaceAfter=0.5*inch,
            spaceBefore=0.5*inch
        )

        header_table.setStyle(TableStyle([
            ("ALIGN", (0, 0), (0, -1), "RIGHT"),
            ("LINEBELOW", (1, 0), (1, -1), 0.25, colors.black),
        ]))

        story.append(header_table)

        ingredient_data = [[
            "Ingredients",
            "Amount",
            "Put Out",
            "Left Over",
        ]]

        ingredients = meal.get_ingredients()

        for ingredient, [amount, uom] in ingredients.items():
            ingredient_data.append([
                ingredient.title(),
                f"{amount} {uom}",
            ])

        ingredient_table = Table(
            ingredient_data, colWidths=(4*inch, "*", "*", "*")
        )
        ingredient_table.setStyle(TableStyle([
            ("BOX", (0, 0), (-1, -1), 0.25, colors.black),
            ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.black),
            ("LINEBELOW", (0, 0), (-1, 0), 2, colors.black),
            ("LINEBELOW", (0, 0), (-1, 0), 2, colors.black),
            ("ALIGN", (1, 0), (-1, 0), "CENTER")
        ]))

        story.append(ingredient_table)
        f = Frame(0.5*inch, 0.5*inch, 7.5*inch, 10*inch)
        f.hAlign = "LEFT"
        f.addFromList(story, p)
        p.showPage()

    p.save()

    buffer.seek(0)
    return FileResponse(buffer, filename='meals.pdf')

meals/templates/meals/add.html
{% extends "base.html" %}

{% block content %}
  <main class="mt-4">
    <div class="container">
      <div class="content">
        <h1 class="title">Choose {% if has_fruit %}Fruit{% endif %}{% if has_fruit and has_veggies %} and{% endif %} {% if has_veggies%}Vegetable{% endif %}</h1>
      </div>
      <div class="columns">
        <div role="region" aria-label="Meal list information" class="column is-one-third">
          <p>Use the form to the right to specify which {% if has_fruit %}fruit{% endif %}{% if has_fruit and has_veggies %} and{% endif %} {% if has_veggies%}vegetable{% endif %} will be served with this meal.</p>
        </div>
        <div role="region" aria-label="Meal scheduling form" class="column is-one-half">
          {% if form %}
            <div class="content box">
              <form method="post">
                {% csrf_token %}
                {% if has_fruit %}
                  <div class="field">
                    <label class="label" for="id_fruit">Fruit:</label>
                    <div class="control">
                      <div>
                          {{ form.fruit }}
                          <a href="{% url "create_fruit" meal.id %}" class="button ml-4 is-info is-outlined">New Fruit</a>
                      </div>
                    </div>
                  </div>
                  <div class="field">
                    <label class="label" for="id_fruit_quantity">Amount per person:</label>
                    <p>{{form.errors.fruit_quantity}}</p>
                    <div class="control">
                      <div>
                          {{ form.fruit_quantity }}
                      </div>
                    </div>
                  </div>
                {% endif %}
                {% if has_veggies %}
                  <div class="field">
                    <label class="label" for="id_vegetable">Vegetable:</label>
                    <div class="control">
                      <div>
                          {{ form.vegetable }}
                          <a href="{% url "create_vegetable" meal.id %}" class="button ml-4 is-info is-outlined">New Vegetable</a>
                      </div>
                    </div>
                  </div>
                  <div class="field">
                    <label class="label" for="id_vegetable_quantity">Amount per person:</label>
                    <p>{{form.errors.fruit_quantity}}</p>
                    <div class="control">
                          {{ form.vegetable_quantity }}
                    </div>
                  </div>
                {% endif %}
                <div class="buttons">
                  <input class="button is-primary mt-4 mr-4" type="submit" value="Add">
                </div>
              </form>
            </div>
          {% endif %}
        </div>
      </div>
    </div>
  </main>
{% endblock %}

meals/templates/meals/create_ingredient.html
{% extends "base.html" %}

{% block content %}
  <main class="mt-4">
    <div class="container">
      <div class="content">
        <h1 class="title">Create new ingredient</h1>
      </div>
      <div class="columns">
        <div role="region" aria-label="Recipe form information" class="column is-one-third">
          <p>Create a new ingredient using the form to the right.</p>
          <p>This will create an ingredient that is available to use on any recipe.</p>
        </div>
        <div role="region" aria-label="Recipe creation form" class="column is-one-quarter box">
          <form method="post">
            {{ form.as_bulma }}
            {% csrf_token %}
            <div class="controls">
              <button class="button is-primary mt-4">Create ingredient</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

meals/templates/meals/create_meal.html
{% extends "base.html" %}

{% block content %}
  <main class="mt-4">
    <div class="container">
      <div class="content">
        <h1 class="title">Schedule meal</h1>
      </div>
      <div class="columns">
        <div role="region" aria-label="Meal list information" class="column is-one-third">
          <p> Schedule a meal using the form to the right</p>
        </div>
        <div role="region" aria-label="Meal scheduling form" class="column is-one-quarter box">
          <form method="post">
            {{ meal_form.as_bulma }}
            {% csrf_token %}
            <div class="controls">
              <button class="button is-primary mt-4">Schedule meal</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

meals/templates/meals/create_order.html
{% extends "base.html" %}

{% block content %}
  <main class="mt-4">
    <div class="container">
      <div class="content">
        <h1 class="title">Create order</h1>
      </div>
      <div class="columns">
        <div role="region" aria-label="Order form information" class="column is-one-third">
          <p>Create a new order using the form to the right.</p>
          <p>Meals can be added to the order in the next step</p>
        </div>
        <div role="region" aria-label="Order creation form" class="column is-one-quarter box">
          <form method="post">
            {{ form.as_bulma }}
            {% csrf_token %}
            <div class="controls">
              <button class="button is-primary mt-4">Create Order</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

meals/templates/meals/create_recipe.html
{% extends "base.html" %}

{% block content %}
  <main class="mt-4">
    <div class="container">
      <div class="content">
        <h1 class="title">Create recipe</h1>
      </div>
      <div class="columns">
        <div role="region" aria-label="Recipe form information" class="column is-one-third">
          <p>Create a new recipe using the form to the right.</p>
        </div>
        <div role="region" aria-label="Recipe creation form" class="column is-one-quarter box">
          <form method="post">
            {{ form.as_bulma }}
            {% csrf_token %}
            <div class="controls">
              <button class="button is-primary mt-4">Create recipe</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

meals/templates/meals/delete_meal.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-4">
    <div class="columns content is-centered">
      <div class="column is-one-third">
        <h1>Delete Meal</h1>
        <p>
          Are you sure you want to delete {{ object }}
        </p>
        <form action="{% url "delete_meal" object.id %}" method="post">
          {% csrf_token %}
          <div class="buttons">
            <input class="button is-danger is-outlined has-text-centered" type="submit" value="Yes">
            <a class="button is-black is-outlined" style="align-items: baseline;" href="{% url "edit_meal" object.id %}">No</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

meals/templates/meals/delete_recipe.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-4">
    <div class="columns content is-centered">
      <div class="column is-one-third">
        <h1>Delete Recipe</h1>
        <p>
          Are you sure you want to delete {{ object }}
        </p>
        <form action="{% url "delete_recipe" object.id %}" method="post">
          {% csrf_token %}
          <div class="buttons">
            <input class="button is-danger is-outlined has-text-centered" type="submit" value="Yes">
            <a class="button is-black is-outlined" style="align-items: baseline;" href="{% url "update_recipe" object.id %}">No</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

meals/templates/meals/list.html
{% extends "base.html" %}

{% block content %}
  <main class="mt-4">
    <div class="container">
      <div class="content">
        <h1 class="title">Meals</h1>
      </div>
      <div class="columns">
        <div role="region" aria-label="Meal list information" class="column is-one-quarter">
          <div class="buttons">
            <a class="button is-info is-outlined" href="{% url "schedule_meal" %}">Schedule Meal</a>
            <a class="button is-info is-outlined" target="_blank" href="{% url "print_meal" %}">Print Meals</a>
          </div>
          <p>A list of all of the scheduled meals after today.</p>
        </div>
        <div role="region" aria-label="Meal list" class="column is-three-quarters box">
          <table class="table is-striped is-hoverable is-fullwidth">
            <thead>
              <tr>
                <th>Date</th>
                <th>Meal</th>
                <th>Planned</th>
                <th>Actual</th>
                <th>Order #</th>
                <th></th>
              </tr>
            </thead>
            {% for meal in meals %}
              <tr>
                <td>{{ meal.date }}</td>
                <td>{{ meal.recipe.name }}</td>
                <td>{{ meal.planned }}</td>
                <td>
                  {% if meal.actual %}
                    {{ meal.actual }}
                  {% else %}
                    -
                  {% endif %}
                </td>
                <td class="{% if meal.order and meal.order.is_complete%}has-background-success{% else %}has-background-danger{% endif %} has-text-white">
                  {% if meal.order %}
                    #{{ meal.order.id }}
                    {% if meal.order.is_complete %}
                      - ordered
                    {% else %}
                      - not ordered
                    {% endif %}
                  {% else %}
                    -
                  {% endif %}
                </td>
                <td>
                  <a class="button is-text" href={% url "edit_meal" meal.id %}>Edit</a>
                </td>
              </tr>
            {% endfor %}
          </table>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

meals/templates/meals/order_list.html
{% extends "base.html" %}

{% block content %}
  <main class="mt-4">
    <div class="container">
      <div class="content">
        <h1 class="title">Orders</h1>
      </div>
      <div class="columns">
        <div role="region" aria-label="Order list information" class="column is-one-quarter">
          <div class="buttons">
            <a class="button is-info is-outlined" href="{% url "create_order" %}">New Order</a>
            <a class="button is-info is-outlined" target="_blank" href="{% url "print_orders" %}">Print Orders</a>
          </div>
          <p>A list of all orders.</p>
          <p>
            {% comment %} <p class="mt-4">Planned Features</p>
            <ul>
              <li> - Ability to see if a meal has been purchased or not</li>
              <li> - Ability to filter meals</li>
            </ul> {% endcomment %}
          </p>
        </div>
        <div role="region" aria-label="Order list" class="column is-three-quarters box">
          <table class="table is-striped is-hoverable is-fullwidth">
            <thead>
              <tr>
                <th>Order #</th>
                <th>Date</th>
                <th>Completed</th>
                <th>Meals in Order</th>
                <th></th>
              </tr>
            </thead>
            {% for order in order_list %}
              <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.date }}</td>
                <td>
                  {% if order.is_complete %}
                    Yes
                  {% else %}
                    No
                  {% endif %}
                </td>
                <td>{{ order.meals.count }}</td>
                <td><a class="button is-text" href={% url "update_order" order.id %}>Edit</a></td>
              </tr>
            {% endfor %}
          </table>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

meals/templates/meals/recipe_list.html
{% extends "base.html" %}

{% block content %}
  <main class="mt-4">
    <div class="container">
      <div class="content">
        <h1 class="title">Recipes</h1>
      </div>
      <div class="columns">
        <div role="region" aria-label="Recipe list information" class="column is-one-quarter">
          <a class="button is-info is-outlined mb-4" href="{% url "create_recipe" %}">New Recipe</a>
          <p>A list of all of the recipes both active and inactive.</p>
          <p>
            {% comment %} Future Features
            <ul class="list">
              <li> - </li>
              <li> - </li>
              <li> - </li>
            </ul> {% endcomment %}
          </p>
        </div>
        <div role="region" aria-label="Recipe list" class="column is-three-quarters box">
          <table class="table is-striped is-hoverable">
            <thead>
              <tr>
                <th> Name</th>
                <th>Ingredient Count</th>
                <th>Status</th>
                <th>Ingredients</th>
                <th></th>
              </tr>
            </thead>
            {% for recipe in recipes %}
              {% with ingredients=recipe.ingredients.all %}
                <tr>
                  <td>{{ recipe.name.title }}</td>
                  <td>{{ ingredients.count }}</td>
                  <td>{% if recipe.is_active %}Active{% else %}Inactive{% endif %}</td>
                  <td>
                    {% for ingredient in ingredients.all %}
                      {% if forloop.last %}
                        {{ ingredient.name }}
                      {% else %}
                        {{ ingredient.name }},
                      {% endif %}
                    {% endfor %}
                  </td>
                  <td>
                    <a class="button is-text" href={% url "update_recipe" recipe.id %}>Edit</a>
                  </td>
                </tr>
              {% endwith %}
            {% endfor %}
          </table>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

meals/templates/meals/update_meal.html
{% extends "base.html" %}

{% block content %}
  <main class="mt-4">
    <div class="container">
      <div class="content">
        <h1 class="title">Update meal</h1>
      </div>
      <div class="columns">
        <div role="region" aria-label="Meal list information" class="column is-one-third">
          <p>Use the form to the right to update this meal.</p>
        </div>
        <div role="region" aria-label="Meal scheduling form" class="column is-one-third box">
          <form method="post">
            {{ form.as_bulma }}
            {% csrf_token %}
            {% comment %} <div class="buttons"> {% endcomment %}
              <input class="button is-primary mt-4 mr-4" type="submit" value="Update">
              <a class="button is-danger mt-4" style="align-items: baseline;" href={% url "delete_meal" object.id %}>Delete</a>
            {% comment %} </div> {% endcomment %}
          </form>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

meals/templates/meals/update_order.html
{% extends "base.html" %}

{% block content %}
  <main class="mt-4">
    <div class="container">
      <div class="content">
        <h1 class="title">Update order</h1>
      </div>
      <div class="columns">
        <div role="region" aria-label="Order update directions" class="column is-one-quarter">
          <p>Use the form to the right to update this order.</p>
        </div>
        <div role="region" aria-label="Order update form" class="column is-half">
          <div class="content box">
            <div class="columns">
              <div class="column">
                <form method="post">
                  {{ form.as_bulma }}
                  {% csrf_token %}
                  <input class="button is-primary is-outlined mt-4 mr-4" type="submit" value="Done">
                  {% comment %} <a class="button is-danger is-outlined mt-4" style="align-items: baseline;" href={% url "delete_recipe" object.id %}>Delete</a> {% endcomment %}
                </form>
              </div>
              <div class="column">
                <form method="post" action="{% url "add_meals_to_order" object.id%}">
                  {{ meal_form.as_bulma}}
                  {% if no_meals %}
                    <p>No meals to add to order.</p>
                  {% else %}
                    <input class="button is-primary is-outlined mt-4 mr-4" type="submit" value="Add">
                  {% endif %}
                  {% csrf_token %}
                </form>
              </div>
            </div>
          </div>
          <div class="content box">
            <p class="label">Meals Added to Order:</p>
            <table class="table">
              <th>Date</th>
              <th>Meal</th>
              <th></th>
              {% for meal in order.meals.all %}
                <tr>
                  <td>{{ meal.date }}</td>
                  <td>{{ meal.recipe }}</td>
                  <td><a class="button is-text" href="{% url "remove_meal_from_order" object.id meal.id %}">Remove</a></td>
                </tr>
              {% empty %}
                <tr>
                  <td>---</td>
                  <td>---</td>
                </tr>
              {% endfor %}
            </table>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

meals/templates/meals/update_recipe_ingredient.html
{% extends "base.html" %}

{% block content %}
  <main class="mt-4">
    <div class="container">
      <div class="content">
        <h1 class="title">Update recipe ingredient</h1>
      </div>
      <div class="columns">
        <div role="region" aria-label="Meal list information" class="column is-one-third">
          <p>Use the form to the right to the ingredient for .</p>
        </div>
        <div role="region" aria-label="Meal scheduling form" class="column is-one-third box">
          <form method="post">
            {{ form.as_bulma }}
            {% csrf_token %}
            {% comment %} <div class="buttons"> {% endcomment %}
              <input class="button is-primary mt-4 mr-4" type="submit" value="Update">
              <a class="button is-danger mt-4" style="align-items: baseline;" href={% url "delete_meal" object.id %}>Delete</a>
            {% comment %} </div> {% endcomment %}
          </form>
        </div>
      </div>
    </div>
  </main>
{% endblock %}